version:  '3.9'
services:
  backend:
    container_name: mspurchase
    restart: always
    build:  .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    networks:
      host:

  rabbitmq:
    restart: always
    image:  rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER:  "joel"
      RABBITMQ_DEFAULT_PASS:  "joel123"
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      host:

networks:
  host: