name: Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  tests:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./mspurchase/pom.xml
  
  build:
    needs: tests
    name: Build maven package
    runs-on: ubuntu-latest   

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./mspurchase/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build package jar
        run: mvn -B package -DskipTests --file ./mspurchase/pom.xml
      - name: Upload .jar
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./mspurchase/target/mspurchase-0.0.1-SNAPSHOT.jar
  deploy:
    needs: build
    name: Deploy on AWS Elastic Beanstall
    runs-on: ubuntu-latest
    steps:
      - name: Dowload jar
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          wait_for_environment_recovery: 120
          application_name: app-purchase
          environment_name: Apppurchase-env-1
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: mspurchase-0.0.1-SNAPSHOT.jar
